# syntax=docker/dockerfile:1
FROM python:3.12-slim

# optional
ENV PYTHONUNBUFFERED=1

WORKDIR /env/
COPY requirements.txt /env/
RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app/

COPY app/ /app/

CMD ["fastapi", "run", "/app/main.py", "--port", "80"]